### ISSUE TITLE
Authentication With GraphQL

### ISSUE THREAD

**Issue by ansarizafar** [serverless/serverless-graphql-blog#1]
Thanks for amazing work and blog post. I want to mention that graphQL can also be used for authentication. Check this article https://medium.com/front-end-developers/graphql-field-guide-to-auth-ead84f657ab#.gn3hectew.

**Comment by kevinold** [comment]
Thanks for sharing.  I'm looking into ways to incorporate something of this nature with GraphQL and Serverless.
