### ISSUE TITLE
Deployment problem with role for function

### ISSUE THREAD

**Issue by helloniklas** [serverless/serverless-graphql-blog#14]
I get this when trying to deploy this,

Failed to deploy the following functions in "dev" to the following regions:  
Serverless: us-east-1 ------------------------  
Serverless:   graphql: The role defined for the function cannot be assumed by Lambda.  
/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:61
        fn = function () { throw arg; };

**Comment by helloniklas** [comment]
This now works after cleaning everything out on AWS and rerunning deploy.

**Comment by xaidrian** [comment]
I am running into this same problem.  I am new to AWS so would you mind being more specific in terms of what you cleaned out of AWS?
