### ISSUE TITLE
Up code to serverless 1.5

### ISSUE THREAD

**Issue by rderocle** [serverless/serverless-graphql-blog#22]
Hi guys,

great project !
could you upgrade your code to new serverless 1.5 ?
thanks.

**Comment by malonehedges** [comment]
I think this is what is causing me issues...
New to Serverless and can't get the commands to work properly. `serverless project install serverless-graphql-blog` says that project isn't a command, and similarly `serverless dash summary` doesn't recognize dash as a command.

**Comment by quantuminformation** [comment]
What needs to happen to upgrade it to 1.5, is it difficult?

**Comment by HoraceShmorace** [comment]
How do we get this to work with the latest version of serverless?

**Comment by nikgraf** [comment]
Happy to accept a PR, but unfortunately I nor someone else familiar with GraphQL for the team has time to do this in the near future.
