### ISSUE TITLE
Updates needed for serverless 0.4?

### ISSUE THREAD

**Issue by weitzman** [serverless/serverless-graphql-blog#8]
Any updates you would make based on serverless .4? For example, the release notes say "If you have s-modules.json in your project, we will continue to support those, but we advise you to change them into s-resources-cf.json files."

Perhaps make a few issues and folks will submit PRs.

**Comment by kevinold** [comment]
Yes I'll update the structure soon. 

On February 24, 2016 at 9:46:58 PM PST, Moshe Weitzman notifications@github.com wrote:Any updates you would make based on serverless .4? For example, the release notes say "If you have s-modules.json in your project, we will continue to support those, but we advise you to change them into s-resources-cf.json files."  Perhaps make a few issues and folks will submit PRs.  —Reply to this email directly or view it on GitHub.

**Comment by weitzman** [comment]
Serverless .5 was released.

**Comment by kevinold** [comment]
Fixed in https://github.com/serverless/serverless-graphql-blog/issues/11#issuecomment-222585378
